services:
  pg: # generic name for the service
    image: bitnami/postgresql # by default looks for the image in the docker hub
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=upload
    volumes:
      - './docker:/docker-entrypoint-initdb.d'
      - 'db:/var/lib/postgresql/data'

  widget-server:
    build: . # By default look to the Dockerfile
    container_name: widget-server
    ports:
      - '3000:3333'
    environment:
      - CLOUDFARE_ACCOUNT_ID=#
      - CLOUDFARE_ACCESS_KEY_ID=#
      - CLOUDFARE_SECRET_ACCESS_KEY=#
      - CLOUDFARE_BUCKET=#
      - CLOUDFARE_PUBLIC_URL=http://localhost:5432
      - DATABASE_URL=postgresql://pg:5432/upload

volumes:
  db:
