services:
  pg: # generic name for the service
    image: bitnami/postgresql # by default looks for the image in the docker hub
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    volumes:
      - './docker:/docker-entrypoint-initdb.d'
      - 'db:/var/lib/postgresql/data'

  widget-server:
    build: . # By default look to the Dockerfile
    container_name: widget-server
    ports:
      - '3000:3333'
    environment:
      - CLOUDFARE_ACCOUNT_ID=$CLOUDFARE_ACCOUNT_ID
      - CLOUDFARE_ACCESS_KEY_ID=$CLOUDFARE_ACCESS_KEY_ID
      - CLOUDFARE_SECRET_ACCESS_KEY=$CLOUDFARE_SECRET_ACCESS_KEY
      - CLOUDFARE_BUCKET=$CLOUDFARE_BUCKET
      - CLOUDFARE_PUBLIC_URL=$CLOUDFARE_PUBLIC_URL
      - DATABASE_URL=$DATABASE_URL

volumes:
  db:
